# Generated by Django 3.2 on 2021-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='msg_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
